"""Unit-test vector generator for CborRedactNoSig (verified CBOR parse tree +
MSO-style salted digest list).

The vector is a nested CWT-like payload exercising integer keys (including a
2-byte negative key, -260), 1/2/4-byte heads, tstr/uint scalar values, map and
array subtree values, and a 2-hop path (-260 -> 1) to the subject map.

Usage:
  python3 cbor.py         # writes cbor_redact.circom, input.json, expected_output.json
  python3 cbor.py check   # compares witness.json against expected_output.json

Uses cwt_redact.cbor_tree (stdlib-only) as the single source of truth for the
item-table witness format.
"""
import json
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
from cwt_redact.cbor_tree import (build_item_table, encode, mso_message,
                                  tree_witness)

MAX_KEY_LEN = 8
MAX_VALUE_LEN = 64
MAX_PATH_KEY_LEN = 8
NAMESPACE = b"org.iso.18013.5.1.acts"
PATH = [-260, 1]

CREDENTIAL = {
    1: "AT",                                   # int key, short tstr
    4: 1620000000,                             # uint value with 4-byte head
    -260: {                                    # 2-byte negative key
        1: {                                   # subject map
            "ver": "1.2.1",
            "nam": {"fn": "Rossi", "gn": "Mario"},        # map subtree value
            "dob": "1990-01-01",
            "v": [{"tg": "840539006", "dn": 2}],          # array subtree value
        },
    },
}


def item_randoms(n):
    # deterministic "randomness" so the expected output is a fixed test vector
    return [bytes((17 * i + j) % 256 for j in range(16)) for i in range(n)]


CIRCUIT = """pragma circom 2.0.3;

// AUTO-GENERATED by cbor.py — do not edit by hand.
include "../../cbor_redact_verify.circom";

component main {{ public [namespace, pathKeyLen, pathKey] }} = CborRedactNoSig({payload_len}, {max_items}, {n_fields}, {max_key_len}, {max_value_len}, {path_depth}, {max_path_key_len}, {ns_len});
"""


def generate(script_dir):
    payload = encode(CREDENTIAL)
    inputs, items, subj, entries = tree_witness(payload, PATH,
                                                max_path_key_len=MAX_PATH_KEY_LEN)
    n_fields = len(entries)
    randoms = item_randoms(n_fields)

    (script_dir / "cbor_redact.circom").write_text(CIRCUIT.format(
        payload_len=len(payload), max_items=len(items), n_fields=n_fields,
        max_key_len=MAX_KEY_LEN, max_value_len=MAX_VALUE_LEN,
        path_depth=len(PATH), max_path_key_len=MAX_PATH_KEY_LEN,
        ns_len=len(NAMESPACE)))

    inputs.update({
        "payload": list(payload),
        "itemRandom": [list(r) for r in randoms],
        "namespace": list(NAMESPACE),
    })
    with open(script_dir / "input.json", "w") as f:
        json.dump(inputs, f, indent=2)

    msg = mso_message(payload, items, entries, randoms, NAMESPACE,
                      MAX_KEY_LEN, MAX_VALUE_LEN)
    with open(script_dir / "expected_output.json", "w") as f:
        json.dump({"message": list(msg)}, f, indent=2)

    print(f"payload: {len(payload)}B, items: {len(items)}, subject: {subj}")
    print("Files written: cbor_redact.circom, input.json, expected_output.json")


def check(script_dir):
    with open(script_dir / "expected_output.json") as f:
        expected = json.load(f)["message"]
    with open(script_dir / "witness.json") as f:
        wit = json.load(f)
    got = [int(x) for x in wit[1:1 + len(expected)]]
    assert got == expected, "circuit message does not match expected_output.json"
    print("CBOR tree parse + MSO digest-list unit test PASSED")


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        check(here)
    else:
        generate(here)
