"""Unit-test vector generator for CborRedactNoSig (parser + mdoc redaction).

Usage:
  python3 cbor.py         # writes cbor_redact.circom, input.json, expected_output.json
  python3 cbor.py check   # compares witness.json against expected_output.json

Self-contained on purpose (no imports from cwt_redact/), mirroring the style
of the emsa/mgf unit tests.
"""
import json
import sys
from pathlib import Path

N_FIELDS = 4
MAX_KEY_LEN = 32
MAX_VALUE_LEN = 64
NAMESPACE = b"org.iso.18013.5.1.acts"
PLACEHOLDER = 0x00
MASK = [1, 0, 1, 0]

# Exercises: short/1-byte-extended headers for both keys and values,
# tstr and bstr values, and an empty value.
CLAIMS = [
    ("family_name", "Rossi", 3),                                  # short key, short tstr
    ("a_quite_long_claim_key_name_x", "y", 3),                    # extended key (29 > 23)
    ("portrait", bytes(range(40)), 2),                            # short key, extended bstr
    ("note", "", 3),                                              # empty value
]


def enc_head(major, n):
    if n < 24:
        return bytes([(major << 5) | n])
    if n < 256:
        return bytes([(major << 5) | 24, n])
    raise ValueError("length too large for the minimal CBOR subset")


def encode_payload():
    payload = enc_head(5, N_FIELDS)
    fields = []
    for key, value, major in CLAIMS:
        kb = key.encode()
        vb = value.encode() if isinstance(value, str) else bytes(value)
        payload += enc_head(3, len(kb)) + kb + enc_head(major, len(vb)) + vb
        fields.append((kb, vb, major))
    return payload, fields


def item_randoms():
    # deterministic "randomness" so the expected output is a fixed test vector
    return [bytes((17 * i + j) % 256 for j in range(16)) for i in range(N_FIELDS)]


def expected_message(fields):
    randoms = item_randoms()
    msg = bytes([len(NAMESPACE)]) + NAMESPACE + bytes([N_FIELDS])
    for i, (kb, vb, major) in enumerate(fields):
        disclosed = MASK[i]
        item = bytes([i, disclosed])
        item += randoms[i] if disclosed else bytes([PLACEHOLDER]) * 16
        item += bytes([major if disclosed else PLACEHOLDER])
        item += bytes([len(kb)]) + kb + b"\x00" * (MAX_KEY_LEN - len(kb))
        item += bytes([len(vb) if disclosed else PLACEHOLDER])
        if disclosed:
            item += vb + b"\x00" * (MAX_VALUE_LEN - len(vb))
        else:
            item += bytes([PLACEHOLDER]) * MAX_VALUE_LEN
        msg += item
    return msg


CIRCUIT = """pragma circom 2.0.3;

// AUTO-GENERATED by cbor.py — do not edit by hand.
include "../../cbor_redact_verify.circom";

component main {{ public [mask, namespace] }} = CborRedactNoSig({payload_len}, {n_fields}, {max_key_len}, {max_value_len}, {ns_len}, {placeholder});
"""


def generate(script_dir):
    payload, fields = encode_payload()
    (script_dir / "cbor_redact.circom").write_text(CIRCUIT.format(
        payload_len=len(payload), n_fields=N_FIELDS, max_key_len=MAX_KEY_LEN,
        max_value_len=MAX_VALUE_LEN, ns_len=len(NAMESPACE), placeholder=PLACEHOLDER))

    with open(script_dir / "input.json", "w") as f:
        json.dump({
            "payload": list(payload),
            "mask": MASK,
            "keyLen": [len(kb) for kb, _, _ in fields],
            "valLen": [len(vb) for _, vb, _ in fields],
            "valMajor": [major for _, _, major in fields],
            "itemRandom": [list(r) for r in item_randoms()],
            "namespace": list(NAMESPACE),
        }, f, indent=2)

    with open(script_dir / "expected_output.json", "w") as f:
        json.dump({"message": list(expected_message(fields))}, f, indent=2)

    print("Files written: cbor_redact.circom, input.json, expected_output.json")


def check(script_dir):
    with open(script_dir / "expected_output.json") as f:
        expected = json.load(f)["message"]
    with open(script_dir / "witness.json") as f:
        wit = json.load(f)
    got = [int(x) for x in wit[1:1 + len(expected)]]
    assert got == expected, "circuit message does not match expected_output.json"
    print("CBOR parse + mdoc redaction unit test PASSED")


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        check(here)
    else:
        generate(here)
