"""Unit test of CborRedactVerify against a REAL credential from the internet:
the official EU Digital COVID Certificate test vector CO1 ("VALID: RSA 2048
key", alg PS256), taken from the public dataset
https://github.com/eu-digital-green-certificates/dgc-testdata
(common/2DCode/raw/CO1.json, vendored here as eudcc_CO1.json).

The circuit under test is the full redaction stage (blinding excluded):
  1. issuer RSA-PSS signature verification over the COSE_Sign1 Sig_structure
     (CoseSign1Verify: real protected header with kid, 307-byte payload,
     PS256 salt recovered from the signature);
  2. verified CBOR parse tree of the real payload (48 items) and public-path
     selection of the subject map at -260,1 (the eu_dgc_v1 map: v, nam, ver,
     dob);
  3. MSO-style salted digest list over the 4 entries, checked byte-per-byte
     against the Python reference (deterministic salts, fixed test vector).

Witness generation succeeds only if the signature, the tree decomposition
and the path checks all hold; the final compare pins the digest list.

Usage:
  python3 cose_real.py         # writes cose_real.circom, input.json, expected_output.json
  python3 cose_real.py check   # compares witness.json against expected_output.json

Requires the `cryptography` package (see requirements.txt).
"""
import base64
import hashlib
import json
import sys
from pathlib import Path

from cryptography import x509
from cryptography.hazmat.primitives import hashes
from cryptography.hazmat.primitives.asymmetric import padding

sys.path.insert(0, str(Path(__file__).resolve().parents[3]))
from cwt_redact.cbor_tree import mso_message, tree_witness

HASH_LEN = 32
SALT_LEN = 32
EM_LEN = 256
W_LIMB = 64
K_LIMBS = 32

PATH = [-260, 1]
MAX_PATH_KEY_LEN = 8
NAMESPACE = b"org.iso.18013.5.1.acts"


def rd_head(b, i):
    """Read one CBOR head; returns (major type, argument, next index)."""
    ib = b[i]
    mt, ai = ib >> 5, ib & 31
    i += 1
    if ai < 24:
        return mt, ai, i
    if ai == 24:
        return mt, b[i], i + 1
    if ai == 25:
        return mt, int.from_bytes(b[i:i + 2], "big"), i + 2
    if ai == 26:
        return mt, int.from_bytes(b[i:i + 4], "big"), i + 4
    raise ValueError("unsupported CBOR head")


def parse_cose_sign1(cose):
    """Extract (protected, payload, signature) from a COSE_Sign1 message."""
    i = 0
    mt, val, i = rd_head(cose, i)
    if mt == 6:  # CBOR tag 18 (COSE_Sign1)
        mt, val, i = rd_head(cose, i)
    assert mt == 4 and val == 4, "not a COSE_Sign1 array"
    items = []
    for _ in range(4):
        mt, n, i = rd_head(cose, i)
        if mt == 2:  # bstr
            items.append(cose[i:i + n])
            i += n
        elif mt == 5:  # unprotected header map: skip
            items.append(None)
            for _ in range(n):
                for _ in range(2):
                    mt2, n2, i = rd_head(cose, i)
                    if mt2 in (2, 3):
                        i += n2
        else:
            raise ValueError("unexpected item in COSE_Sign1")
    prot, _, payload, sig = items
    return prot, payload, sig


def sig_structure(prot, payload):
    prot_hdr = bytes([0x40 + len(prot)]) if len(prot) < 24 else bytes([0x58, len(prot)])
    pl_hdr = bytes([0x58, len(payload)]) if len(payload) < 256 else b"\x59" + len(payload).to_bytes(2, "big")
    return b"\x84" + b"\x6aSignature1" + prot_hdr + prot + b"\x40" + pl_hdr + payload


def mgf1(seed, mask_len):
    counter, output = 0, b""
    while len(output) < mask_len:
        output += hashlib.sha256(seed + counter.to_bytes(4, "big")).digest()
        counter += 1
    return output[:mask_len]


def recover_pss_salt(sig, e, n, tbs):
    em = pow(int.from_bytes(sig, "big"), e, n).to_bytes(EM_LEN, "big")
    assert em[-1] == 0xBC
    db_len = EM_LEN - HASH_LEN - 1
    db = bytes(a ^ b for a, b in zip(em[:db_len], mgf1(em[db_len:db_len + HASH_LEN], db_len)))
    db = bytes([db[0] & 0x7F]) + db[1:]
    salt = db[-SALT_LEN:]
    m_hash = hashlib.sha256(tbs).digest()
    assert hashlib.sha256(b"\x00" * 8 + m_hash + salt).digest() == em[db_len:db_len + HASH_LEN]
    return salt


def limbs(n, k=K_LIMBS, w=W_LIMB):
    mask = (1 << w) - 1
    return [str((n >> (w * i)) & mask) for i in range(k)]


def item_randoms(n):
    # deterministic "randomness" so the expected output is a fixed test vector
    return [bytes((23 * i + 7 * j) % 256 for j in range(16)) for i in range(n)]


CIRCUIT = """pragma circom 2.0.3;

// AUTO-GENERATED by cose_real.py — do not edit by hand.
include "../../cbor_redact_verify.circom";

component main {{ public [issuerExp, issuerModulus, namespace, pathKeyLen, pathKey] }} = CborRedactVerify(64, 32, 17, 7, {payload_len}, {prot_len}, {max_items}, {n_fields}, {max_key_len}, {max_value_len}, {path_depth}, {max_path_key_len}, {ns_len});
"""


def load_vector(script_dir):
    d = json.loads((script_dir / "eudcc_CO1.json").read_text())
    prot, payload, sig = parse_cose_sign1(bytes.fromhex(d["COSE"]))
    cert = x509.load_der_x509_certificate(base64.b64decode(d["TESTCTX"]["CERTIFICATE"]))
    pk = cert.public_key()
    nums = pk.public_numbers()
    tbs = sig_structure(prot, payload)
    # sanity check outside the circuit before generating the test vector
    pk.verify(sig, tbs,
              padding.PSS(mgf=padding.MGF1(hashes.SHA256()), salt_length=SALT_LEN),
              hashes.SHA256())
    return prot, payload, sig, nums, tbs


def generate(script_dir):
    prot, payload, sig, nums, tbs = load_vector(script_dir)
    salt = recover_pss_salt(sig, nums.e, nums.n, tbs)

    tree_inputs, items, subj, entries = tree_witness(
        payload, PATH, max_path_key_len=MAX_PATH_KEY_LEN)
    n_fields = len(entries)
    randoms = item_randoms(n_fields)
    max_key_len = max(items[k]["end"] - items[k]["off"] for k, _ in entries)
    max_value_len = max(items[v]["end"] - items[v]["off"] for _, v in entries)

    (script_dir / "cose_real.circom").write_text(CIRCUIT.format(
        payload_len=len(payload), prot_len=len(prot), max_items=len(items),
        n_fields=n_fields, max_key_len=max_key_len, max_value_len=max_value_len,
        path_depth=len(PATH), max_path_key_len=MAX_PATH_KEY_LEN,
        ns_len=len(NAMESPACE)))

    inputs = {
        "payload": list(payload),
        "prot": list(prot),
        "issuerSig": limbs(int.from_bytes(sig, "big")),
        "issuerPssSalt": list(salt),
        "issuerExp": limbs(nums.e),
        "issuerModulus": limbs(nums.n),
        "itemRandom": [list(r) for r in randoms],
        "namespace": list(NAMESPACE),
    }
    inputs.update(tree_inputs)
    with open(script_dir / "input.json", "w") as f:
        json.dump(inputs, f, indent=2)

    msg = mso_message(payload, items, entries, randoms, NAMESPACE,
                      max_key_len, max_value_len)
    with open(script_dir / "expected_output.json", "w") as f:
        json.dump({"message": list(msg)}, f, indent=2)

    print(f"Real EUDCC (PS256, RSA-2048) verified off-circuit; payload {len(payload)}B, "
          f"{len(items)} items, subject at item {subj} with {n_fields} entries")
    print("Files written: cose_real.circom, input.json, expected_output.json")


def check(script_dir):
    with open(script_dir / "expected_output.json") as f:
        expected = json.load(f)["message"]
    with open(script_dir / "witness.json") as f:
        wit = json.load(f)
    got = [int(x) for x in wit[1:1 + len(expected)]]
    assert got == expected, "circuit digest list does not match expected_output.json"
    print("Real-EUDCC signature + parse tree + salted digest list unit test PASSED")


if __name__ == "__main__":
    here = Path(__file__).resolve().parent
    if len(sys.argv) > 1 and sys.argv[1] == "check":
        check(here)
    else:
        generate(here)
